export const profile = {
  name: 'Pamindu Karunadasa',
  email: 'pamindu39@gmail.com',
  github: 'https://github.com/CodeJediX',
  linkedin: 'https://www.linkedin.com/in/pamindu-karunadasa',
  linktree: 'https://linktr.ee/PaminduKarunadasa',
  site: 'https://codejedix.github.io/portfolio-Pamindu/',
};

// Editorially curated; provenance and omitted claims are recorded in docs/RESEARCH.md.
export const projects = [
  {
    id: 'signspeak', name: 'SignSpeak', category: 'Applied AI', filters: ['ai'],
    label: 'Computer vision · Accessible learning', color: 'blue',
    summary: 'Bringing sign recognition, speech, and an articulated 3D hand into one learning experience.',
    image: 'signspeak.webp', alt: 'SignSpeak browser recognition interface with model and camera controls',
    repo: 'https://github.com/CodeJediX/signspeak', demo: 'https://codejedix.github.io/signspeak/sign_viewer.html',
    stack: ['Python', 'TensorFlow', 'MediaPipe', 'JavaScript', 'Three.js'],
    status: 'Competition prototype', context: 'Team Quantum-X · Data Odyssey finalist',
    role: 'Team contributor: sign recognition, model training and testing, vocabulary expansion, web development, 3D visualization, and deployment.',
    problem: 'Learning a sign involves both understanding its movement and getting useful feedback when practicing it. A static word list cannot provide that interaction.',
    solution: 'SignSpeak connects webcam landmark tracking with a sign vocabulary, speech output, and a browser-based 3D hand viewer. The Python pipeline supports collecting sequences, training an LSTM classifier, and evaluating recognition.',
    architecture: ['Webcam input', 'MediaPipe landmarks', 'Sequence recognition', 'Text + speech / 3D viewer'],
    features: ['Webcam-based hand landmark tracking and vocabulary matching.', 'Two-layer LSTM training pipeline for temporal gesture sequences.', 'Articulated hand visualization and speech feedback.', 'Separate scripts for dataset auditing, collection, training, and evaluation.'],
    challenge: 'Gesture recognition depends on sequences, not just individual frames. The training code uses temporal landmark features and regularization; the browser also has a built-in landmark matcher.',
    limits: 'The browser landmark matcher and Python classifier are separate paths. Using the trained classifier in the browser requires a TensorFlow.js conversion. This is a learning prototype; recognition accuracy is not presented as a verified production metric.',
    gallery: [],
    sources: [['Repository and implementation', 'https://github.com/CodeJediX/signspeak'], ['Contribution and competition context', profile.linkedin]],
  },
  {
    id: 'leaflens', name: 'LeafLens', category: 'Applied AI', filters: ['ai'],
    label: 'Machine learning · Agriculture', color: 'green',
    summary: 'A crop-health prototype that turns leaf images into paddy disease and tea-quality assessments.',
    image: 'leaflens.webp', alt: 'LeafLens application showing its crop image analysis interface',
    repo: 'https://github.com/CodeJediX/LeafLens_Project',
    demo: 'https://youtu.be/FJXr0ydCo-0', demoLabel: 'Watch demonstration',
    stack: ['Python', 'TensorFlow', 'Keras', 'Streamlit', 'Docker'],
    status: 'Demonstrated prototype', context: 'Agricultural image classification',
    role: 'Project work spanning the machine-learning pipeline and application delivery, documented in the public repository and profile.',
    problem: 'Farmers need understandable information about visible crop damage and leaf quality. A model alone is not a usable interface for that task.',
    solution: 'LeafLens combines image classification with a Streamlit application for paddy disease and tea-quality assessment. The project includes model-training notebooks, model assets, and packaging for local use.',
    architecture: ['Leaf image', 'Image preprocessing', 'TensorFlow / Keras model', 'Streamlit assessment'],
    features: ['Separate paddy disease and tea-quality workflows.', 'Transfer-learning-based image classification.', 'An image-based interface with assessment guidance.', 'Docker and standalone packaging documented by the project.'],
    challenge: 'The engineering work extends beyond training: image preparation, model loading, and presenting the result all need to work together in an application people can use.',
    limits: 'Presented as an agricultural AI prototype. No independently verified field accuracy, yield improvement, or deployment impact is claimed. Image-based results need agricultural validation.',
    gallery: [{src:'leaflens-detail.webp',alt:'Second LeafLens screenshot showing an assessment result'}],
    sources: [['Source and packaging', 'https://github.com/CodeJediX/LeafLens_Project'], ['Project demonstration', 'https://youtu.be/FJXr0ydCo-0']],
  },
  {
    id: 'magen', name: 'MAGEN', category: 'Software & systems', filters: ['software','ai'],
    label: 'Desktop automation · Computer vision', color: 'dark',
    summary: 'A voice-driven Windows assistant connecting conversation, camera input, and practical desktop controls.',
    image: 'magen.webp', alt: 'MAGEN desktop assistant dashboard with system telemetry and camera preview',
    repo: 'https://github.com/CodeJediX/Magen-AI-Assistant',
    stack: ['Python', 'Flask', 'Gemini', 'OpenCV', 'Windows APIs'],
    status: 'Local desktop prototype', context: 'Multimodal assistant',
    role: 'Built and integrated the assistant, its voice and vision modules, Windows controls, and web dashboard.',
    problem: 'A conversational assistant becomes more useful when it can act on the computer around it and respond to visual context, rather than only return text.',
    solution: 'MAGEN routes spoken commands to Windows controls or a Gemini conversation. A Flask interface exposes camera streaming, assistant status, and system telemetry. Separate modules handle speech, vision, memory, and device interactions.',
    architecture: ['Voice / camera', 'Command routing', 'Gemini or Windows control', 'Speech + Flask dashboard'],
    features: ['Voice-command routing and conversational responses.', 'Camera capture and image-based prompts.', 'Volume and screen-brightness controls through Windows integrations.', 'Local memory and a dashboard for CPU, memory, and assistant status.'],
    challenge: 'The voice loop runs alongside the Flask interface. Windows audio control also needs COM initialization in the worker thread, a concrete integration detail handled in the source.',
    limits: 'Requires Windows, local dependencies, and a configured Gemini API key. Some commands open system settings rather than directly change connectivity. No autonomous smart-home deployment is claimed.',
    gallery: [{src:'magen-detail.webp',alt:'Additional MAGEN interface showing assistant controls'}],
    sources: [['Application source', 'https://github.com/CodeJediX/Magen-AI-Assistant/blob/main/app.py'], ['Windows controls', 'https://github.com/CodeJediX/Magen-AI-Assistant/blob/main/home.py']],
  },
  {
    id: 'createx', name: 'CreateX 3.0', category: 'Web & design', filters: ['web','software'],
    label: 'Competition platform · Interactive design', color: 'sand',
    summary: 'A cinematic competition website backed by participant registration and organizer workflows.',
    image: 'createx.webp', alt: 'Original mythology-inspired artwork from the CreateX 3.0 project',
    repo: 'https://github.com/CodeJediX/cre8x-3-scrollytelling', demo: 'https://cre8x-3-scrollytelling.vercel.app',
    stack: ['Next.js', 'React', 'TypeScript', 'Supabase', 'PostgreSQL'],
    status: 'Public website · Platform implementation', context: 'UI/UX competition experience',
    role: 'Web and platform development represented in my public repository; the competition identity and supplied artwork belong to the event.',
    problem: 'A competition needs a memorable public identity and practical ways to manage participants, teams, and submissions.',
    solution: 'CreateX combines a scroll-driven visual story with application routes for registration, participant dashboards, and an organizer console. Supabase provides authentication, database access, and storage.',
    architecture: ['Next.js interface', 'Validated application routes', 'Supabase authentication', 'PostgreSQL + private storage'],
    features: ['A public experience organized around a future-focused design journey.', 'Solo and team registration flows and participant dashboards.', 'Organizer tooling for rounds, eligibility, announcements, and submissions.', 'SQL migrations for row-level security and database constraints.'],
    challenge: 'Visual storytelling and operational workflows have different needs. The code separates the public experience from registration and administration, with access rules represented in database migrations.',
    limits: 'The public presentation is live. Repository features describe the implementation, not independently tested end-to-end operation of every organizer workflow or evidence of event adoption.',
    gallery: [],
    sources: [['Implementation and architecture', 'https://github.com/CodeJediX/cre8x-3-scrollytelling'], ['Public experience', 'https://cre8x-3-scrollytelling.vercel.app']],
  },
  {
    id: 'signspeak-junior', name: 'SignSpeak Junior', category: 'Applied AI', filters: ['ai','software'],
    label: 'On-device intelligence · Inclusive interfaces', color: 'pink',
    summary: 'A child-friendly sentence builder with speech output and locally running word suggestions.',
    image: 'junior.webp', alt: 'SignSpeak Junior mobile sentence builder with word cards and AI helper suggestions',
    repo: 'https://github.com/CodeJediX/signspeak-junior-ai-mobile',
    stack: ['JavaScript', 'HTML / CSS', 'On-device NLP', 'Android TTS'],
    status: 'v2.0 Android prototype', context: 'Communication and language practice',
    role: 'Developed the companion mobile application and its communication-focused interface, as described in my project announcement.',
    problem: 'Young users can benefit from an interface that lets them construct and hear short sentences without relying on a keyboard or a cloud AI service.',
    solution: 'The application uses large vocabulary cards, sentence playback, and an on-device helper. Its compact intent model and transition model rank possible next words and help reorder short sentences.',
    architecture: ['Vocabulary cards', 'Local intent + transition model', 'Sentence builder', 'Text-to-speech'],
    features: ['Picture or emoji vocabulary cards and quick phrases.', 'Local intent prediction and next-word ranking.', 'Favorites, recent words, and customizable vocabulary.', 'Parent settings and Android speech output, with a browser speech fallback.'],
    challenge: 'The helper is packaged with the interface rather than calling a remote language model. Suggestions can use the current sentence, favorites, and recent vocabulary without sending the sentence to a cloud AI endpoint.',
    limits: 'A communication prototype, not a clinical product. The repository preserves an APK and extracted web bundle, not the original Gradle project. Picture mode may request online images; it is not a fully offline image library.',
    gallery: [],
    sources: [['Version, screenshots, and implementation notes', 'https://github.com/CodeJediX/signspeak-junior-ai-mobile']],
  },
  {
    id: 'hotel-management', name: 'Hotel Management', category: 'Software & systems', filters: ['software'],
    label: 'Desktop application · Relational data', color: 'stone',
    summary: 'A Windows application bringing customer records, rooms, and reservations into a single workflow.',
    image: 'hotel.webp', alt: 'Hotel management Windows Forms application sign-in screen',
    repo: 'https://github.com/CodeJediX/HotelManagementSystem',
    stack: ['C#', '.NET Framework', 'Windows Forms', 'SQLite'],
    status: 'Desktop project', context: 'Hotel operations',
    role: 'Developed the desktop application, documented in my public project profile and C# repository.',
    problem: 'Room availability, customer records, and reservations need to remain connected when a booking is made.',
    solution: 'A Windows Forms interface organizes client, room, and booking workflows around a local SQLite database. Booking code validates a client, checks room availability, records a reservation, and updates the room state.',
    architecture: ['Windows Forms UI', 'Booking validation', 'SQLite queries', 'Rooms + reservations'],
    features: ['Customer and room management screens.', 'Reservation creation with client and room checks.', 'Local relational persistence using SQLite.', 'A desktop interface designed around front-desk workflows.'],
    challenge: 'The core engineering concern is connecting interface actions to persistent state: a reservation must refer to an existing customer and reflect room availability.',
    limits: 'Shown as a learning and application-development project. Multi-user concurrency, production security, and use by an operating hotel have not been independently established.',
    gallery: [{src:'hotel-detail.webp',alt:'Hotel management application room and reservation screen'}],
    sources: [['C# source and database integration', 'https://github.com/CodeJediX/HotelManagementSystem']],
  },
];
